site_name: ResponseBot
docs_dir: docs/

repo_name: 'G0-G4/ResponseBot'
repo_url: 'https://github.com/G0-G4/ResponseBot'
theme: readthedocs
nav:
  - About: index.md
  - Параметры:
    - Параметры: params.md
    - Режимы генерации отзывов: generators.md
    - Подстановка значений: substitute.md
  - Использование программы:
    - Начало работы: startfiles.md
    - Структура файлов: structure.md
    - Выгрузка куки файла: cookies.md
    - Обновление: update.md
plugins:
  - search:
      enabled: true
      lang:
        - en
        - ru
